### ISSUE TITLE
USB cannot be initialized.

### ISSUE THREAD

**Issue by EulaliaVelda** [t123yh/BM32#1]
SnVzdCBhIHJvdXRpbmUgcmVwb3J0LgoKT0ssIEkgbWVzc2VkIHVwLgpUaGVyZSBpcyBzb21ldGhpbmcgYXMgY3JhenkgYXMgImNvbGxlY3RpdmUgYWNjb3VudCIgd2hpY2ggb3V0cHV0cyBtZWFuaW5nbGVzcyBkYXRhLCBnb29kIGxlc3Nvbi4KQnV0IEkgZG9uJ3QgY2FyZSwgdGhlIHByb2Nlc3MgY2FuIGJlIHJlaW5pdGlhdGVkIHdpdGggZGlmZmVyZW50IHBhcmFtZXRlcjogd2l0aCAweGRlYWRiZWVmJ3MgcGhvbmUuClRoZSByZWluaXRpYXRpb24gdGltaW5nIGRlcGVuZHMgb24gdGhlIGhvbmVzdHkgb2YgdGhlIGNvdW50ZXJwYXJ0LgoKVGhlIGJyb2FkY2FzdCBvZiB0aGlzIG1lc3NhZ2Ugd2lsbCBiZSBlbmRlZCB3aGVuIGEgc3VjY2Vzc2Z1bCBUQ1AgY29ubmVjdGlvbiBlc3RhYmxpc2hlZC4KClJlZ2FyZHMsCgpUaGUgQ2hpY2tzLg

**Comment by t123yh** [comment]
Just a routine report.

OK, I messed up.
There is something as crazy as "collective account" which outputs meaningless data, good lesson.
But I don't care, the process can be reinitiated with different parameter: with 0xdeadbeef's phone.
The reinitiation timing depends on the honesty of the counterpart.

The broadcast of this message will be ended when a successful TCP connection established.

Regards,

The Chicks
